package com.pex.pex_courier.dto.order

import android.os.Parcelable
import com.google.gson.annotations.SerializedName
import kotlinx.parcelize.Parcelize


@Parcelize
data class OrderDTO(
    @SerializedName("id_asal"                 ) var idAsal                  : Int?    = 0,
    @SerializedName("id_tujuan"               ) var idTujuan                : Int?    = 0,
    @SerializedName("id_pegawai"              ) var idPegawai               : Int?    = null,
    @SerializedName("id"                      ) var id                      : Int?    = null,
    @SerializedName("nm_kurir"                ) var nm_kurir                : String? = "-",
    @SerializedName("nomorpemesanan"          ) var nomorpemesanan          : String? = null,
    @SerializedName("nomortracking"           ) var nomortracking           : String? = null,
    @SerializedName("pelangganbaru"           ) var pelangganbaru           : String? = null,
    @SerializedName("namapengirim"            ) var namapengirim            : String? = null,
    @SerializedName("teleponpengirim"         ) var teleponpengirim         : String? = null,
    @SerializedName("emailpengirim"           ) var emailpengirim           : String? = null,
    @SerializedName("provinsipengirim"        ) var provinsipengirim        : String? = null,
    @SerializedName("kotapengirim"            ) var kotapengirim            : String? = null,
    @SerializedName("kecamatanpengirim"       ) var kecamatanpengirim       : Int?    = null,
    @SerializedName("gkecamatanpengirim"      ) var gkecamatanpengirim      : String? = null,
    @SerializedName("alamatpengirim"          ) var alamatpengirim          : String? = null,
    @SerializedName("latpengirim"             ) var latpengirim             : String? = null,
    @SerializedName("longpengirim"            ) var longpengirim            : String? = null,
    @SerializedName("catatanpengirim"         ) var catatanpengirim         : String? = null,
    @SerializedName("namapenerima"            ) var namapenerima            : String? = null,
    @SerializedName("teleponpenerima"         ) var teleponpenerima         : String? = null,
    @SerializedName("provinsipenerima"        ) var provinsipenerima        : String? = null,
    @SerializedName("kotapenerima"            ) var kotapenerima            : String? = null,
    @SerializedName("kecamatanpenerima"       ) var kecamatanpenerima       : Int?    = null,
    @SerializedName("gkecamatanpenerima"      ) var gkecamatanpenerima      : String? = null,
    @SerializedName("alamatpenerima"          ) var alamatpenerima          : String? = null,
    @SerializedName("latpenerima"             ) var latpenerima             : String? = null,
    @SerializedName("longpenerima"            ) var longpenerima            : String? = null,
    @SerializedName("catatanpenerima"         ) var catatanpenerima         : String? = null,
    @SerializedName("tipepengiriman"          ) var tipepengiriman          : String? = null,
    @SerializedName("jenisbarang"             ) var jenisbarang             : String? = null,
    @SerializedName("jenispengiriman"         ) var jenispengiriman         : Int?    = null,
    @SerializedName("jenisukuran"             ) var jenisukuran             : String? = null,
    @SerializedName("jaraktempuh"             ) var jaraktempuh             : String? = null,
    @SerializedName("panjang"                 ) var panjang                 : String? = null,
    @SerializedName("lebar"                   ) var lebar                   : String? = null,
    @SerializedName("tinggi"                  ) var tinggi                  : String? = null,
    @SerializedName("berat"                   ) var berat                   : String? = null,
    @SerializedName("biaya"                   ) var biaya                   : String? = null,
    @SerializedName("trdiskon"                ) var trdiskon                : Int?    = null,
    @SerializedName("iddiskon"                ) var iddiskon                : String? = null,
    @SerializedName("jenispembayaran"         ) var jenispembayaran         : Int?    = null,
    @SerializedName("tanggalpickup"           ) var tanggalpickup           : String? = null,
    @SerializedName("catatanipembayaran"      ) var catatanipembayaran      : String? = null,
    @SerializedName("statusangkut"            ) var statusangkut            : String? = null,
    @SerializedName("statuspengiriman"        ) var statuspengiriman        : Int?    = null,
    @SerializedName("idbyrvirtual"            ) var idbyrvirtual            : String? = null,
    @SerializedName("tdmanual"                ) var tdmanual                : String? = null,
    @SerializedName("usercreate"              ) var usercreate              : String? = null,
    @SerializedName("tglcreate"               ) var tglcreate               : String? = null,
    @SerializedName("usermodify"              ) var usermodify              : String? = null,
    @SerializedName("tglmodify"               ) var tglmodify               : String? = null,
    @SerializedName("shipment_type"           ) var shipmentType            : String? = null,
    @SerializedName("id_pengiriman"           ) var idPengiriman            : Int?    = null,
    @SerializedName("status_pengiriman"       ) var statusPengiriman        : String? = null,
    @SerializedName("layanan"                 ) var layanan                 : String? = null,
    @SerializedName("reffno"                  ) var reffno                  : Int?    = null,
    @SerializedName("namakurirpickup"         ) var namakurirpickup         : Int?    = null,
    @SerializedName("tanggalpenugasanpickup"  ) var tanggalpenugasanpickup  : String? = null,
    @SerializedName("jampenugasanpickup"      ) var jampenugasanpickup      : String? = null,
    @SerializedName("tanggalpenugasanshuttle" ) var tanggalpenugasanshuttle : String? = null,
    @SerializedName("jampenugasanshuttle"     ) var jampenugasanshuttle     : String? = null,
    @SerializedName("tglpenugasandelivery"    ) var tanggalpenugasandelivery: String? = null,
    @SerializedName("jampenugasandelivery"    ) var jampenugasandelivery    : String? = null,
    @SerializedName("tglpending"              ) var tanggalpending          : String? = null,
    @SerializedName("jampending"              ) var jampending              : String? = null,
    @SerializedName("tglpenugasankembali"     ) var tanggalpenugasankembali : String? = null,
    @SerializedName("jampenugasankembali"     ) var jampenugasankembali     : String? = null,
    @SerializedName("jampickup"               ) var jampickup               : String? = null,
    @SerializedName("panjangaktual"           ) var panjangaktual           : String? = null,
    @SerializedName("lebaraktual"             ) var lebaraktual             : String? = null,
    @SerializedName("tinggiaktual"            ) var tinggiaktual            : String? = null,
    @SerializedName("berataktual"             ) var berataktual             : String? = null,
    @SerializedName("tarifaktual"             ) var tarifaktual             : String? = null,
    @SerializedName("diserahkanoleh"          ) var diserahkanoleh          : String? = null,
    @SerializedName("fotomenyerahkan"         ) var fotomenyerahkan         : String? = null,
    @SerializedName("namakurirdelivery"       ) var namakurirdelivery       : String? = null,
    @SerializedName("tanggaldelivery"         ) var tanggaldelivery         : String? = null,
    @SerializedName("jamdelivery"             ) var jamdelivery             : String? = null,
    @SerializedName("diserahkanolehdelivery"  ) var diserahkanolehdelivery  : String? = null,
    @SerializedName("fotomenyerahkandelivery" ) var fotomenyerahkandelivery : String? = null,
    @SerializedName("namakurirshuttle"        ) var namakurirshuttle        : String? = null,
    @SerializedName("tglbatal"                ) var tglbatal                : String? = null,
    @SerializedName("jambatal"                ) var jambatal                : String? = null,
    @SerializedName("cabang"                  ) var cabang                  : String? = null,
    @SerializedName("id_ukuran"               ) var idUkuran                : Int?    = 0,
    @SerializedName("kodejenisukuran"         ) var kodejenisukuran         : String? = null,
    @SerializedName("maksimalpanjang"         ) var maksimalpanjang         : String? = null,
    @SerializedName("maksimallebar"           ) var maksimallebar           : String? = null,
    @SerializedName("maksimaltinggi"          ) var maksimaltinggi          : String? = null,
    @SerializedName("maksimalberat"           ) var maksimalberat           : String? = null,
    @SerializedName("satuanpanjang"           ) var satuanpanjang           : String? = null,
    @SerializedName("isactive"                ) var isactive                : Int?    = null,
    @SerializedName("nama_jenis_pembayaran"   ) var namaJenisPembayaran     : String? = null,
    @SerializedName("namajenisbarang"         ) var namaJenisBarang         : String? = null,
    @SerializedName("statusdelivery"          ) var statusdelivery          : Int?    = 0,
    @SerializedName("kodeasuransi"            ) var kodeasuransi            : String? = null,
    @SerializedName("biayaasuransi"           ) var biayaasuransi           : Int?    = 0,


) : Parcelable
